[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mrkn/mrkn256.vim'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme mrkn256
'''

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repo = 'astashov/vim-ruby-debugger'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'vim-scripts/TwitVim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'takkii/vim-trick'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'fatih/vim-go'
